resource_group_name                            = "rg-webDataQueue-ussc-dev"
region                                         = "ussc"
environment                                    = "dev"
location                                       = "South Central US"
resource_tags                                  = {}
vpn_gateway_client_configuration_address_space = ["192.168.0.0/24"]
api_management_sku                             = "Developer_1"
app_service_plan_sku                           = "P1V2"
api_management_publisher_name                  = "Contoso"
api_management_publisher_email                 = "jordanbean@microsoft.com"
admin_upn                                      = "jordanbean_microsoft.com#EXT#@MngEnv472967.onmicrosoft.com"
