resource_group_name                            = "rg-webDataQueue-ussc-dev"
region                                         = "ussc"
environment                                    = "dev"
location                                       = "South Central US"
resource_tags                                  = {}
vpn_gateway_client_configuration_address_space = ["192.168.0.0/24"]
api_management_sku                             = "Developer_1"
app_service_plan_sku                           = "P1V2"
api_management_publisher_name                  = "Contoso"
api_management_publisher_email                 = "jordanbean@microsoft.com"
admin_upn                                      = "be7346a1-f02d-4514-8e52-14295d7d5d24"
pipeline_spn_object_id                         = "e9ee9d6b-ab60-439c-88aa-be1d97f4dfe4"
