variables:
  devEnvironmentName: dev
  devResourceGroupName: rg-webDataQueue-ussc-dev
  devBackendAzureRmContainerName: tfstate
  devBackendAzureRmResourceGroupName: rg-webDataQueue-ussc-dev
  devBackendAzureRmStorageAccountName: sawebdataqueuetfstate
  devBackendAzureRmKey: terraform.tfstate
  devServiceConnectionName: rg-webDataQueue-ussc-dev
  devAppServiceName: wa-webPortal-webDataQueue-ussc-dev